[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x1c61c2"
blue = "0x00ff00"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.dim]
black = "0x1c61c2"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.normal]
black = "0x123e7c"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Light Italic"

[font.normal]
family = "Fira Code"
style = "Light"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.9

[window.dimensions]
columns = 80
lines = 24
